### DISCUSSION TITLE
Including systematics variation samples

### DISCUSSION THREAD

**Discussion by Tomoya-Iizawa** [scikit-hep/cabinetry#433] [Q&A] [answered]
Hi,

I would like to include different generator samples as systematics sample, but could someone tell me how I can do that? 
I think systematics can be implemented as following,

```yaml
Systematics:
  - Name: "Signal_modeling"
    Up:
      SamplePath: "modeling_variation_up.root"
    Down:
      SamplePath: "modeling_variation_down.root"
    Samples: "Signal"
```

but for the generator difference, I would like to include different file as ttbar-syst-Sh2212.root, and would like to use one of the histogram (not as Up and Down) in that file.

Best Regards,
Tomoya

**Comment by alexander-held** [comment, marked as answer]
Hi Tomoya, an example for how to set this up is here:
https://github.com/scikit-hep/cabinetry/blob/a0638e18a6b7940c015c177a5b93f3167237e793/utils/config_histograms.yml#L31-L37

If you want to read a histogram from a different file you could set it up like this for example:
```yaml
General:
    InputPath: "{SamplePath}:{RegionPath}"

Samples:
  - Name: "ttbar"
    SamplePath: "ttbar-PP8.root"

Systematics:
  - Name: "ttbar_Sherpa"
    Up:
      SamplePath: "ttbar-syst-Sh2212.root"
    Down:
      Symmetrize: True
    Samples: "ttbar"
    Type: "NormPlusShape" 
```
This will build the `ttbar` sample using histograms from a file `ttbar-PP8.root` and the `ttbar_Sherpa` variation by switching to `ttbar-syst-Sh2212.root`. See also https://cabinetry.readthedocs.io/en/latest/core.html#inputs-to-cabinetry-ntuples-or-histograms for the relevant documentation.

**Reply by Tomoya-Iizawa** [reply]
thank you for the answer!
Could you tell me how to indicate histogram named as e.g. "nominal" in ttbar-syst-Sh2212.root ?
Is the following correct implementation?

```yaml
  - Name: "ttbar_Sherpa"
    Up:
      SamplePath: "ttbar-syst-Sh2212.root"
      VariationPath: "nominal"
    Down:
      Symmetrize: True
    Samples: "ttbar"
    Type: "NormPlusShape"
```

Added: this may not be working since the expected limit and its +/- 1, 2 sigma are not changed at all w/ and w/o including this while the prior distribution of PP8 and Sherpa are rather different. And seeing the created workspace, the bin contents are exactly same between PP8 and Sherpa.

**Reply by alexander-held** [reply]
How does your `InputPath` option in `General` look like? The idea behind this system is that you can have placeholders in brackets like `{VariationPath}` which are then filled in via configuration options that are specific to e.g. a given systematic variation like in your example. You presumably would want something like `InputPath: "{SamplePath}:{VariationPath}"`.

**Reply by Tomoya-Iizawa** [reply]
thanks, it is written as following, now I understood and it seems not necessary to set VariationPath.

```yaml
  InputPath: "to_be_set_at_execution/{SamplePath}.root:{RegionPath}/{VariationPath}"
  VariationPath: "nominal"
```

Now I set as

```yaml
Samples:
  - Name: "ttbar"
    SamplePath: "ttbar"

Systematics:
  - Name: "ttbar-Sh2212"
    Up:
      SamplePath: "ttbar-syst-Sh2212"
    Down:
      Symmetrize: True
    Type: "NormPlusShape"
    Samples: ["ttbar"]
```

but PP8 and sherpa have same bin contents if I see the created workspace (.json file in workspace directory). do you have any idea how to resolve this? maybe PP8 sample is readout while I am trying to read Sherpa sample by some reason?
