### DISCUSSION TITLE
variation_path support in ntuple builder

### DISCUSSION THREAD

**Discussion by rihoppe** [scikit-hep/cabinetry#527] [Q&A]
Hi,

I have been trying to add some systematics to my configuration and got confused somehow.
I'm trying to add my samples directly from the ntuples, for this I have multiple folders, each of them for every correction.

somewhat like this:
```
Nominal/
├── Sgn.root
├── Bkg1.root
└── Bkg2.root
Correction_up/
├── Sgn.root
├── Bkg1.root
└── Bkg2.root
Correction_down/
├── Sgn.root
├── Bkg1.root
└── Bkg2.root
```
obviously I simplified things a little here, but from the documentation I found that if I were using histograms directly I could do something like this
```python
General:
  InputPath: "/SomePath/{VariationPath}/{SamplePath}:{Tree}"

Samples:
  - Name: "Sgn"
      Tree: "tree"
      SamplePath: "Sgn.root"
  - Name: "Bkg1"
      Tree: "tree"
      SamplePath: "Bkg1.root"
  - Name: "Bkg2"
      Tree: "tree"
      SamplePath: "Bkg2.root"

Systematics:
  - Name: "systematic"
      Up:
        VariationPath: "Correction_up"
      Down:
        VariationPath: "Correction_down"
      Samples: ["Sgn", "Bkg1", "Bkg2"]
      Type: "NormPlusShape"
```
But for the ntuple builder, "VariationPath" is not an option.

Is there a simpler way which I'm missing? or do I have to make the histograms separatelly in order to use "VariationPath"

I also found some old Issue regarding this (#435), where it says that "tree" might capture this functionality, but I dont see how in this case

Thanks in advance

**Comment by alexander-held** [comment]
Hi, I believe your use case does not fit well within the existing functionality, thanks for reporting this! From what I see right now this is strong motivation for adding `{VariationPath}` for ntuples. The only idea I have at the moment to work around this is to split the systematic definition up per sample, then to use `ModifierName` to keep all systematics defined per sample correlated (in the same way they would be correlated if you defined the systematic for all samples at once). It would roughly look like this:

```yaml
General:
  InputPath: "/SomePath/{SamplePath}:{Tree}"

Samples:
  - Name: "Sgn"
    Tree: "tree"
    SamplePath: "Nominal/Sgn.root

  - Name: "Bkg1"
    Tree: "tree"
    SamplePath: "Nominal/Bkg1.root"

  - Name: "Bkg2"
    Tree: "tree"
    SamplePath: "Nominal/Bkg2.root"

Systematics:
  - Name: "systematic_Sgn"
    Up:
      SamplePath: "Correction_up/Sgn.root"
    Down:
      SamplePath: "Correction_down/Sgn.root"
    Samples: "Sgn"
    Type: "NormPlusShape"
    ModifierName: "systematic"

  - Name: "systematic_ Bkg1"
    Up:
      SamplePath: "Correction_up/Bkg1.root"
    Down:
      SamplePath: "Correction_down/Bkg1.root"
    Samples: "Bkg1"
    Type: "NormPlusShape"
    ModifierName: "systematic"

  - Name: "systematic_ Bkg2"
    Up:
      SamplePath: "Correction_up/Bkg2.root"
    Down:
      SamplePath: "Correction_down/Bkg2.root"
    Samples: "Bkg2"
    Type: "NormPlusShape"
    ModifierName: "systematic"
```

I believe this would work but is much more verbose and much less convenient. We'll have a look at getting `{VariationPath}` added to ntuples, that feels like a good option for such cases.
